#!/bin/bash

INSTALL="sudo pacman -S --noconfirm"

sed -i "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf # Enable the multilib repository in /etc/pacman.conf (steam is located in multilib)

sudo pacman -Syu --noconfirm

$INSTALL  base-devel
git clone https://aur.archlinux.org/yay-git.git
cd yay-git
makepkg -si --noconfirm
cd ~

# Install Steam
$INSTALL steam

$INSTALL virtualbox-host-modules-arch virtualbox

sudo pacman -S --noconfirm alacritty vim 

sudo pacman -S --noconfirm xorg-server sddm plasma-desktop
sudo systemctl enable sddm.service

echo "Installation complete. Reboot when ready"
