#!/bin/bash

sudo pacman -Sy

sudo pacman -S --noconfirm virtualbox-host-modules-arch virtualbox

sudo pacman -S --noconfirm xorg-server sddm plasma-desktop
sudo systemctl enable sddm.service

echo "Installation complete. Reboot when ready"
